apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qaacwzxgi-nodejs 
  janus-idp.io/tekton: qaacwzxgi-nodejs
  backstage.io/kubernetes-id: qaacwzxgi-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qaacwzxgi-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  